apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-scanner
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  url: {{ .Values.discord.webhookUrl | quote }}
